language: ruby
dist: xenial
cache: bundler

env:
  global:
    - JEKYLL_ENV=production

rvm:
  - 2.5

cache: bundler

addons:
  apt:
    update: true
    packages:
      - curl
      - git
      - make
      - ruby-bundler
      - ruby-dev
      - libxml2-dev
      - libxslt-dev
      - nodejs
      - npm
  snaps:
    - jq
    - yq
    - name: aws-cli
      confinement: classic # or devmode
    - name: node
      confinement: classic # or devmode
      channel: 10/stable

install:
  - travis_retry gem install bundler

before_script:
  - bundle
  - npm install

script:
  - bundle exec jekyll build

deploy:
  - provider: script
    script: ./monitor.sh aws s3 sync _site s3://$S3_BUCKET_NAME --region=$AWS_REGION --delete --no-progress
    skip_cleanup: true
    on:
      branch: master

  - provider: script
    script: ./monitor.sh aws s3 sync _site s3://$S3_STAGING_BUCKET_NAME --region=$AWS_REGION --delete --no-progress
    skip_cleanup: true
    on:
      branch: staging

after_deploy:
  - aws configure set preview.cloudfront true
  - test $TRAVIS_BRANCH = "master" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  - test $TRAVIS_BRANCH = "staging" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_STAGING_DISTRIBUTION_ID --paths "/*"
